trigger: none
pr:
  - main
  - v*.*.x

pool:
  name: Default
  demands:
  - AGENT_CI_TARGET -equals ompi
  - MLNX_IB_DEVICE -equals yes

variables:
  ompi_jenkins_scripts_git_repo_url: https://github.com/mellanox-hpc/jenkins_scripts.git
  ompi_jenkins_scripts_git_branch: master
  # Enable debug information, supported values: true, false
  debug: true

jobs:
- job: mellanox_ompi_ci
  displayName: Mellanox Open MPI CI
  timeoutInMinutes: 90
  container:
    image: rdmz-harbor.rdmz.labs.mlnx/hpcx/ompi_ci:latest
    options: -v /hpc/local:/hpc/local -v /opt:/opt --uts=host --ipc=host --ulimit stack=67108864
      --ulimit memlock=-1 --security-opt seccomp=unconfined --cap-add=SYS_ADMIN --device=/dev/infiniband/
  steps:
  - checkout: self
    submodules: true
    path: ompi
    clean: true
  - bash: |
      set -eE
      [ "$(debug)" = "true" ] && set -x
      rm -rf $(Pipeline.Workspace)/jenkins_scripts
      git clone $(ompi_jenkins_scripts_git_repo_url) --branch $(ompi_jenkins_scripts_git_branch) $(Pipeline.Workspace)/jenkins_scripts
      export WORKSPACE=$(Pipeline.Workspace)/ompi
      $(Pipeline.Workspace)/jenkins_scripts/jenkins/ompi/ompi_test.sh
    displayName: Build and test Open MPI
